const queryStatement = "select * from contacts";
// const callbackURL = `/formulas/instances/:id/executions`; USE LATER
const callbackURL = "https://requestbin.com/r/{yourAutoGeneratedBinId}";

done({
    "body":{
        "query": queryStatement,
    },
    "headers":{
        "Elements-Async-Callback-Url": callbackURL
    },
});