const queryStatement = "select * from contacts";
const bulkListenerFormulaInstanceID = 00000;
const callbackURL = `/formulas/instances/${bulkListenerFormulaInstanceID}/executions`; 
// const callbackURL = "https://requestbin.com/r/{yourAutoGeneratedBinId}"; FOR TESTING

done({
    "body": {
        "query": queryStatement
    },
    "headers": {
        "Elements-Async-Callback-Url": callbackURL
    }
});